language: python

python:
- 2.7

script:
- pip install file://$(pwd)

deploy:
  provider: pypi
  user: mottosso
  password:
    secure: TeaVT5oKTkGTHAdkW0fjRIyxD8mbGDh5e7VwjVY/nAmASuX6J+W1IKsmF2lvgKETlbnhNsGl+Lk2YkT5bxRGY4ZI0Hnm4Dewn1Rfq0HdUbTT19gSq86dBHfjZTuq7C5DILIA0SjNfmIQvDsICdj08rkdye+r1fleCtedZAhgkMU=
  on:
    tags: true
    repo: pyblish/pyblish-houdini
